main:
  - name: About
    url: /
    weight: 10
  - name: Research
    url: research/
    weight: 20
  - name: Talks
    url: talks/
    weight: 30
  - name: Teaching
    url: teaching/
    weight: 40
  - name: CV
    url: cv/
    weight: 50
  - name: Contact
    url: contact/

